package de.cit.backend.mgmt.persistence.model;
// Generated 10.12.2017 16:49:45 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import de.cit.backend.mgmt.persistence.model.enums.AgentState;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name = "AGENT", catalog = "citBitDB")
public class AgentDTO extends BaseIdEntity implements java.io.Serializable {

	private Integer id;
	private String ipAddress;
	private int port;
	private AgentState status;
	private Date lastChecked;
	private Set<CapabilityDTO> capabilities;

	public AgentDTO() {
	}

	public AgentDTO(String ipAddress, short port) {
		this.ipAddress = ipAddress;
		this.port = port;
	}

	public AgentDTO(String ipAddress, short port, AgentState status, Date lastChecked,
			Set<PipelineStepDTO> pipelineSteps) {
		this.ipAddress = ipAddress;
		this.port = port;
		this.status = status;
		this.lastChecked = lastChecked;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "IP_ADDRESS", nullable = false, length = 128)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "PORT", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	@Column(name = "STATUS")
	@Enumerated(EnumType.ORDINAL)
	public AgentState getStatus() {
		return this.status;
	}

	public void setStatus(AgentState status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHECKED", length = 19)
	public Date getLastChecked() {
		return this.lastChecked;
	}

	public void setLastChecked(Date lastChecked) {
		this.lastChecked = lastChecked;
	}
	
	@ManyToMany
    @JoinTable(name="AGENT_CAPABILITY",
        joinColumns=
            @JoinColumn(name="AGENT_ID", referencedColumnName="ID"),
        inverseJoinColumns=
            @JoinColumn(name="CAPABILITY_ID", referencedColumnName="ID")
        )
	public Set<CapabilityDTO> getCapabilities() {
		return this.capabilities;
	}

	public void setCapabilities(Set<CapabilityDTO> capabilities) {
		this.capabilities = capabilities;
	}
}
