package de.cit.backend.mgmt.persistence.model;
// Generated 10.12.2017 16:49:45 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pipeline generated by hbm2java
 */
@Entity
@Table(name = "PIPELINE", catalog = "citBitDB")
public class PipelineDTO implements java.io.Serializable {

	private Integer id;
	private ProjectDTO project;
	private String status;
	private String script;
	private Date lastChanged;
	private List<PipelineStepDTO> pipelineSteps = new ArrayList();

	public PipelineDTO() {
	}

	public PipelineDTO(ProjectDTO project, String script) {
		this.project = project;
		this.script = script;
	}

	public PipelineDTO(ProjectDTO project, String status, String script, Date lastChanged, List<PipelineStepDTO> pipelineSteps) {
		this.project = project;
		this.status = status;
		this.script = script;
		this.lastChanged = lastChanged;
		this.pipelineSteps = pipelineSteps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	public ProjectDTO getProject() {
		return this.project;
	}

	public void setProject(ProjectDTO project) {
		this.project = project;
	}

	@Column(name = "STATUS", length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "SCRIPT", nullable = false, length = 256)
	public String getScript() {
		return this.script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED", length = 19)
	public Date getLastChanged() {
		return this.lastChanged;
	}

	public void setLastChanged(Date lastChanged) {
		this.lastChanged = lastChanged;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pipeline")
	public List<PipelineStepDTO> getPipelineSteps() {
		return this.pipelineSteps;
	}

	public void setPipelineSteps(List<PipelineStepDTO> pipelineSteps) {
		this.pipelineSteps = pipelineSteps;
	}

}
