package de.cit.backend.mgmt.persistence.model;
// Generated 10.12.2017 16:49:45 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PipelineStep generated by hbm2java
 */
@Entity
@Table(name = "PIPELINE_STEP", catalog = "citBitDB")
public class PipelineStepDTO implements java.io.Serializable {

	private Integer id;
	private AgentDTO agent;
	private PipelineDTO pipeline;
	private int stepNumber;
	private String script;
	private Set<PipelineStepSuccessors> pipelineStepSuccessorsesForStepId = new HashSet<PipelineStepSuccessors>(0);
	private Set<PipelineStepSuccessors> pipelineStepSuccessorsesForSuccessorId = new HashSet<PipelineStepSuccessors>(0);

	public PipelineStepDTO() {
	}

	public PipelineStepDTO(AgentDTO agent, PipelineDTO pipeline, int stepNumber, String script) {
		this.agent = agent;
		this.pipeline = pipeline;
		this.stepNumber = stepNumber;
		this.script = script;
	}

	public PipelineStepDTO(AgentDTO agent, PipelineDTO pipeline, int stepNumber, String script,
			Set<PipelineStepSuccessors> pipelineStepSuccessorsesForStepId,
			Set<PipelineStepSuccessors> pipelineStepSuccessorsesForSuccessorId) {
		this.agent = agent;
		this.pipeline = pipeline;
		this.stepNumber = stepNumber;
		this.script = script;
		this.pipelineStepSuccessorsesForStepId = pipelineStepSuccessorsesForStepId;
		this.pipelineStepSuccessorsesForSuccessorId = pipelineStepSuccessorsesForSuccessorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AGENT_ID", nullable = false)
	public AgentDTO getAgent() {
		return this.agent;
	}

	public void setAgent(AgentDTO agent) {
		this.agent = agent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PIPELINE_ID", nullable = false)
	public PipelineDTO getPipeline() {
		return this.pipeline;
	}

	public void setPipeline(PipelineDTO pipeline) {
		this.pipeline = pipeline;
	}

	@Column(name = "STEP_NUMBER", nullable = false)
	public int getStepNumber() {
		return this.stepNumber;
	}

	public void setStepNumber(int stepNumber) {
		this.stepNumber = stepNumber;
	}

	@Column(name = "SCRIPT", nullable = false, length = 256)
	public String getScript() {
		return this.script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pipelineStepByStepId")
	public Set<PipelineStepSuccessors> getPipelineStepSuccessorsesForStepId() {
		return this.pipelineStepSuccessorsesForStepId;
	}

	public void setPipelineStepSuccessorsesForStepId(Set<PipelineStepSuccessors> pipelineStepSuccessorsesForStepId) {
		this.pipelineStepSuccessorsesForStepId = pipelineStepSuccessorsesForStepId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pipelineStepBySuccessorId")
	public Set<PipelineStepSuccessors> getPipelineStepSuccessorsesForSuccessorId() {
		return this.pipelineStepSuccessorsesForSuccessorId;
	}

	public void setPipelineStepSuccessorsesForSuccessorId(
			Set<PipelineStepSuccessors> pipelineStepSuccessorsesForSuccessorId) {
		this.pipelineStepSuccessorsesForSuccessorId = pipelineStepSuccessorsesForSuccessorId;
	}

}
