package de.cit.backend.mgmt.persistence.model;
// Generated 10.12.2017 16:49:45 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "PROJECT", catalog = "citBitDB")
public class Project implements java.io.Serializable {

	private Integer id;
	private User userdata;
	private String name;
	private Date createdAt;
	private List<User> projectMembers = new ArrayList<>();
	private List<Pipeline> pipelines = new ArrayList<>();

	public Project() {
	}

	public Project(User userdata, String name, Date createdAt) {
		this.userdata = userdata;
		this.name = name;
		this.createdAt = createdAt;
	}

	public Project(User userdata, String name, Date createdAt, List<User> users,
			List<Pipeline> pipelines) {
		this.userdata = userdata;
		this.name = name;
		this.createdAt = createdAt;
		this.projectMembers = users;
		this.pipelines = pipelines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_USER_ID", nullable = false)
	public User getUserdata() {
		return this.userdata;
	}

	public void setUserdata(User userdata) {
		this.userdata = userdata;
	}

	@Column(name = "NAME", nullable = false, length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_AT", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@ManyToMany(mappedBy="joinedProjects")
	public List<User> getProjectMembers() {
		return this.projectMembers;
	}

	public void setProjectMembers(List<User> users) {
		this.projectMembers = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public List<Pipeline> getPipelines() {
		return this.pipelines;
	}

	public void setPipelines(List<Pipeline> pipelines) {
		this.pipelines = pipelines;
	}

}
