/*
 * bitflow-process-agent: REST-API
 * Process-Agent-REST-API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sven.carlin@campus.tu-berlin.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.cit.backend.agent.api;

import de.cit.backend.agent.ApiException;
import de.cit.backend.agent.api.model.Capability;
import de.cit.backend.agent.api.model.Info;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InfosApi
 */
@Ignore
public class InfosApiTest {

    private final InfosApi api = new InfosApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void capabilitiesGetTest() throws ApiException {
        List<Capability> response = api.capabilitiesGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infoGetTest() throws ApiException {
        Info response = api.infoGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pingGetTest() throws ApiException {
        String response = api.pingGet();

        // TODO: test validations
    }
    
}
