package de.cit.backend.persistence.model;
// Generated 04.12.2017 14:01:29 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name = "AGENT", catalog = "citBitDB")
public class Agent implements java.io.Serializable {

	private Integer id;
	private String ipAddress;
	private short port;
	private String capabilities;
	private Integer status;
	private Date lastChecked;
	private Set<Pipeline> pipelines = new HashSet<Pipeline>(0);

	public Agent() {
	}

	public Agent(String ipAddress, short port) {
		this.ipAddress = ipAddress;
		this.port = port;
	}

	public Agent(String ipAddress, short port, String capabilities, Integer status, Date lastChecked,
			Set<Pipeline> pipelines) {
		this.ipAddress = ipAddress;
		this.port = port;
		this.capabilities = capabilities;
		this.status = status;
		this.lastChecked = lastChecked;
		this.pipelines = pipelines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "IP_ADDRESS", nullable = false, length = 128)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "PORT", nullable = false)
	public short getPort() {
		return this.port;
	}

	public void setPort(short port) {
		this.port = port;
	}

	@Column(name = "CAPABILITIES", length = 256)
	public String getCapabilities() {
		return this.capabilities;
	}

	public void setCapabilities(String capabilities) {
		this.capabilities = capabilities;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHECKED", length = 19)
	public Date getLastChecked() {
		return this.lastChecked;
	}

	public void setLastChecked(Date lastChecked) {
		this.lastChecked = lastChecked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agent")
	public Set<Pipeline> getPipelines() {
		return this.pipelines;
	}

	public void setPipelines(Set<Pipeline> pipelines) {
		this.pipelines = pipelines;
	}

}
