package de.cit.backend.persistence.model;
// Generated 04.12.2017 14:01:29 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PipelineSuccession generated by hbm2java
 */
@Entity
@Table(name = "PIPELINE_SUCCESSION", catalog = "citBitDB", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PIPELINE_ID", "SUCCESSOR_ID" }))
public class PipelineSuccession implements java.io.Serializable {

	private Integer id;
	private Pipeline pipelineByPipelineId;
	private Pipeline pipelineBySuccessorId;

	public PipelineSuccession() {
	}

	public PipelineSuccession(Pipeline pipelineByPipelineId, Pipeline pipelineBySuccessorId) {
		this.pipelineByPipelineId = pipelineByPipelineId;
		this.pipelineBySuccessorId = pipelineBySuccessorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PIPELINE_ID", nullable = false)
	public Pipeline getPipelineByPipelineId() {
		return this.pipelineByPipelineId;
	}

	public void setPipelineByPipelineId(Pipeline pipelineByPipelineId) {
		this.pipelineByPipelineId = pipelineByPipelineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCCESSOR_ID", nullable = false)
	public Pipeline getPipelineBySuccessorId() {
		return this.pipelineBySuccessorId;
	}

	public void setPipelineBySuccessorId(Pipeline pipelineBySuccessorId) {
		this.pipelineBySuccessorId = pipelineBySuccessorId;
	}

}
