package de.cit.backend.persistence.model;
// Generated 04.12.2017 14:01:29 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pipeline generated by hbm2java
 */
@Entity
@Table(name = "PIPELINE", catalog = "citBitDB")
public class Pipeline implements java.io.Serializable {

	private Integer id;
	private Agent agent;
	private Project project;
	private int idOnAgent;
	private String status;
	private String script;
	private int stepNumber;
	private Date lastChanged;
	private Set<PipelineSuccession> pipelineSuccessionsForPipelineId = new HashSet<PipelineSuccession>(0);
	private Set<PipelineSuccession> pipelineSuccessionsForSuccessorId = new HashSet<PipelineSuccession>(0);

	public Pipeline() {
	}

	public Pipeline(Agent agent, Project project, int idOnAgent, int stepNumber) {
		this.agent = agent;
		this.project = project;
		this.idOnAgent = idOnAgent;
		this.stepNumber = stepNumber;
	}

	public Pipeline(Agent agent, Project project, int idOnAgent, String status, String script, int stepNumber,
			Date lastChanged, Set<PipelineSuccession> pipelineSuccessionsForPipelineId,
			Set<PipelineSuccession> pipelineSuccessionsForSuccessorId) {
		this.agent = agent;
		this.project = project;
		this.idOnAgent = idOnAgent;
		this.status = status;
		this.script = script;
		this.stepNumber = stepNumber;
		this.lastChanged = lastChanged;
		this.pipelineSuccessionsForPipelineId = pipelineSuccessionsForPipelineId;
		this.pipelineSuccessionsForSuccessorId = pipelineSuccessionsForSuccessorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AGENT_ID", nullable = false)
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "ID_ON_AGENT", nullable = false)
	public int getIdOnAgent() {
		return this.idOnAgent;
	}

	public void setIdOnAgent(int idOnAgent) {
		this.idOnAgent = idOnAgent;
	}

	@Column(name = "STATUS", length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "SCRIPT", length = 256)
	public String getScript() {
		return this.script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	@Column(name = "STEP_NUMBER", nullable = false)
	public int getStepNumber() {
		return this.stepNumber;
	}

	public void setStepNumber(int stepNumber) {
		this.stepNumber = stepNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CHANGED", length = 19)
	public Date getLastChanged() {
		return this.lastChanged;
	}

	public void setLastChanged(Date lastChanged) {
		this.lastChanged = lastChanged;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pipelineByPipelineId")
	public Set<PipelineSuccession> getPipelineSuccessionsForPipelineId() {
		return this.pipelineSuccessionsForPipelineId;
	}

	public void setPipelineSuccessionsForPipelineId(Set<PipelineSuccession> pipelineSuccessionsForPipelineId) {
		this.pipelineSuccessionsForPipelineId = pipelineSuccessionsForPipelineId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pipelineBySuccessorId")
	public Set<PipelineSuccession> getPipelineSuccessionsForSuccessorId() {
		return this.pipelineSuccessionsForSuccessorId;
	}

	public void setPipelineSuccessionsForSuccessorId(Set<PipelineSuccession> pipelineSuccessionsForSuccessorId) {
		this.pipelineSuccessionsForSuccessorId = pipelineSuccessionsForSuccessorId;
	}

}
