package de.cit.backend.persistence.model;
// Generated 04.12.2017 14:01:29 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Userdata generated by hbm2java
 */
@Entity
@Table(name = "USERDATA", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class Userdata implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private String name;
	private Date registeredSince;
	private Set<UserProject> userProjects = new HashSet<UserProject>(0);
	private Set<Project> projects = new HashSet<Project>(0);

	public Userdata() {
	}

	public Userdata(String email, String password, String name, Date registeredSince) {
		this.email = email;
		this.password = password;
		this.name = name;
		this.registeredSince = registeredSince;
	}

	public Userdata(String email, String password, String name, Date registeredSince, Set<UserProject> userProjects,
			Set<Project> projects) {
		this.email = email;
		this.password = password;
		this.name = name;
		this.registeredSince = registeredSince;
		this.userProjects = userProjects;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "EMAIL", nullable = false, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", nullable = false, length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGISTERED_SINCE", nullable = false, length = 19)
	public Date getRegisteredSince() {
		return this.registeredSince;
	}

	public void setRegisteredSince(Date registeredSince) {
		this.registeredSince = registeredSince;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userdata")
	public Set<UserProject> getUserProjects() {
		return this.userProjects;
	}

	public void setUserProjects(Set<UserProject> userProjects) {
		this.userProjects = userProjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userdata")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
